name: Gia
main: gia\Main
version: 1.0.0
api: [3.0.0]

commands:
  fireball:
    usage: "/fireball"
    permission: op
  lavawave:
    usage: "/lavawave"
    permission: op
  iceball:
    usage: "/iceball"
    permission: op
  icestalactite:
    usage: "/icestalactite"
    permission: op
